### ISSUE TITLE
v4l support

### ISSUE THREAD

**Issue by therishidesai** [oddity-ai/video-rs#42] opened 2024-06-27 02:31 UTC
I want to use video-rs to read from v4l2 devices (USB cameras or v4l2loopback devices). In the past I have had a separate ffmpeg process do the encoding and then use the [v4l crate](https://docs.rs/v4l/latest/v4l/) to read the final encoded values. 

After reading through some of the docs, it seems like I would need to add a new `Location` variant for a `V4lDevice`.

Is this something the video-rs project would want? If so do you have any recommendations on places to start with this integration?

I'd ideally also want to update the RTSP server oddity has implemented to then read from multiple `V4lDevices` and stream them out.

**Comment by gerwin3** [comment] 2024-07-04 11:12
Yes that would be a great addition :)

**Comment by therishidesai** [comment] 2024-07-11 19:36
Since I can't get the encoding working due to the above issue I am using the ffmpeg cli to read from a v4l device and h264 encode it and write to a v4lloopback device. Below is a simple video-rs program that will then read from that loopback device and write to an mp4 file. For some reason when I run this the ffmpeg logs show the following on every call to `muxer.mux`:
```
[mp4 @ 0x555555637340] Packet duration: 7838399151 / dts: 7838399467 is out of range
[mp4 @ 0x555555637340] pts has no value
```

```
fn main() -> Result<()> {
    video_rs::init().unwrap();
    let mut v4l_reader = Reader::new(Path::new("/dev/video5"))?;
    let stream = v4l_reader.best_video_stream_index()?;
    let writer = Writer::new(Path::new("test-video.mp4"))?;
    let mut muxer = MuxerBuilder::new(writer)
        .with_streams(&v4l_reader)
        .unwrap()
        .build();

    // muxer.parameter_sets_h264();
    let mut count = 100000;
    while let Ok(packet) = v4l_reader.read(stream) {
        println!("got packet {:?}", packet.dts());
        if count == 0 {
            break
        }
        muxer.mux(packet)?;
        count = count - 1;
    }

    muxer.finish().unwrap();

    Ok(())
}
```

**Comment by gerwin3** [comment] 2024-07-12 11:27
> So it turns out that I can actually just use a `Location::File` to read from a v4l device. But currently I'm confused as to how I can encode a packet from a `Reader`. I'm using a `Reader` since the raw video from the v4l camera doesn't need to be decoded. `encoder.encode` uses a raw frame but `reader.read` only gives me a `Packet`. I'm not sure how to go from `Packet` to `RawFrame`.

I'm not familiar with v4l but if it produces decoded data then you just need to convert the data (which you can get with `packet.data()`) to whatever is expected. I'm assuming if it is planar RGB for example you'd need to do some transmuting (unsafe rust).

> For some reason when I run this the ffmpeg logs show the following on every call to muxer.mux:

Seems to me that the stream is invalid (the DTS/PTS/duration are likely just garbage values). Maybe it's a raw h264 stream without headers?

**Comment by therishidesai** [comment] 2024-07-12 18:31
Packet doesn't have a data function:

```
error[E0599]: no method named `data` found for struct `video_rs::Packet` in the current scope
  --> examples/v4l-read.rs:26:44
   |
26 |         println!("got packet {:?}", packet.data());
   |                                            ^^^^ method not found in `Packet`
```

**Comment by therishidesai** [comment] 2024-07-12 18:37
> Seems to me that the stream is invalid (the DTS/PTS/duration are likely just garbage values). Maybe it's a raw h264 stream without headers?

The way I am setting up the h264 stream is with the following cli command:

```
ffmpeg -f v4l2 -i /dev/video0 -c:v libx264 -preset ultrafast -f v4l2 /dev/video4
```

One thing I've noticed is that for a while when I call `v4l_reader.read()` I get these messages from the ffmpeg log:

```
[NULL @ 0x55555561e180] non-existing PPS 0 referenced
got packet Time { time: Some(33333), time_base: Rational(1/1000000) }
[NULL @ 0x55555561e180] Decoding VUI
```
So I guess it hasn't gotten a key frame for a while. I then added some more debug prints and for every packet it receives `is_key()` returns false. Not sure why it is never getting a key frame, are there specific reader options I need to pass?

**Comment by gerwin3** [comment] 2024-07-16 12:18
I think it's just that the input stream is not h264 at all. So it is garbage data as far as the decoder is concerned. You need to figure out what data format is provided via v4l

**Comment by gerwin3** [comment] 2024-07-19 12:59
That is kind of weird indeed. To be honest I'm not sure what the issue is. It may be something with ffmpeg. I'll close this issue since v4l is supported through opening the device path.

**Closed by gerwin3** 2024-07-19 12:59 UTC
